### ISSUE TITLE
Implement NIP-46 login in app

### ISSUE THREAD

**Issue by shuesken** [Trustroots/nostroots#47]
We want to allow our users to use their identity for multiple services. In the medium term, this means allowing them to log in with their Trustroots/Nostr identity into other services. (In the long-term, we want this to be handled by a dedicated other service that the user controls and uses to log into Trustroots as well).

We will use the [NIP-46/NIP-05 login flow](https://nips.nostr.com/46#nip-05-login-flow).

As a basic implementation, we need some sample website that acts a "client" and from which the login flow gets started based on the Trustroots username that the user enters. The user can then switch to the Trustroots app and query & approve the login flow. The sample website should then show a successful login.

This is a trial to see if we can implement this basic functionality or run into any hurdles. In the mid-term, we want to make this a very smooth experience and likely use push notifications.

**Comment by guaka** [comment]
There's been some progress with nip-05 login/signup at nomadwiki.org, https://github.com/Trustroots/mediawiki-nostr-auth

Can be added to hitchwiki when it's more stable. HW is a good place to get this to work with the nostroots app because we control it and there are regular new signups, but they end up in a queue and have to wait for an admin/bureaucrat to approve their account. NIP-05 signup would already improve on this (both for user as well as bureaucrats). And NIP-46 with the trustroots app would be great.

**Comment by guaka** [comment]
Seen https://blog.getalby.com/nostr-signer/? This relates to #50 :)
